### ISSUE TITLE
Cloudflare DNS broken - is this really the fix?

### ISSUE THREAD

**Issue by mtis88** [acmesh-official/acme.sh#2888]
I've been using acme.sh with Cloudflare for a while now with no trouble. Today it stopped working. Line 62 in dns_cf evaluated false and therefore returned an error. Line 62 checks that the GET txt records JSON response contains success:true as below:
`if ! printf "%s" "$response" | grep \"success\":true >/dev/null; then`

This line has been there for 4 years. 

Below is the response in my debug output:
`[Tue Apr 28 15:46:26 UTC 2020] response='{
  "result": [],
  "success": true,
  "errors": [],
  "messages": [],
  "result_info": {
    "page": 1,
    "per_page": 20,
    "count": 0,
    "total_count": 0,
    "total_pages": 1
  }
}'`

As of today it seems, line 62 does not parse the response correctly. I had to modify it to include a space before true:
`if ! printf "%s" "$response" | grep \"success\":\ true >/dev/null; then`

It then started working. Am I going crazy?

**Comment by tatablack** [comment]
I was about to open the exact same issue! 😅 
I had been using an older `acme.sh` version; today I decided to update it and start using Cloudflare's new tokens instead of the global API key, and ran into the same problem - fixed in the same way (and I was also puzzled by seeing that the code hadn't been changed in four years).

For context, I used the latest master as of 2 hours ago, on a Synology NAS.

**Comment by gridpane** [comment]
Same here.

Setting up testing domain to get proper output.

**Comment by mtis88** [comment]
I've noticed while doing the PR that DNS records are not being deleted correctly as the parsing of the JSON from the GET call is not extracting the ID of the record correctly.

**Comment by sebile** [comment]
maybe there is a better way to parse the json response from the cloudflare api then using grep, even if the fix proposed by mtis88 in https://github.com/acmesh-official/acme.sh/pull/2890 should be working

**Comment by mtis88** [comment]
Agree. Surely most DNS provider scripts need to parse JSON.

**Comment by tatablack** [comment]
There are also a couple of checks performed using the `_contains` function (which uses `grep` behind the scenes - search for ` _contains "$response" '"success":true'` in the same file.

I'm guessing they may fail as well, but I haven't tested it.

**Comment by mtis88** [comment]
I've made a further change so the id of the DNS record is extracted correctly during the remove record function. However, when using access tokens the response from the delete call returns an error: "DELETE method with API Tokens is not supported by this API". With the global API key the call also errors, but with: "method_not_allowed’. I _hope_ the latter is a temporary problem as it's discussed [here](https://community.cloudflare.com/t/code-1001-error-method-not-allowed/167968). The former however, I'm not sure. The [API docs](https://api.cloudflare.com/#dns-records-for-a-zone-delete-dns-record) include a permission for the delete endpoint ("permission needed: #dns_records:edit") which would imply access token usage no?

**Comment by joecot** [comment]
It seems that cloudflare changed the json response to be pretty printed (or at least adding the spaces in as people are seeing).

I temporarily fixed it by installing the jj utility:
https://github.com/tidwall/jj
Then changing the _cf_rest function in dns_cf.sh from:
```
 if [ "$m" != "GET" ]; then
    _debug data "$data"
    response="$(_post "$data" "$CF_Api/$ep" "" "$m")"
  else
    response="$(_get "$CF_Api/$ep")"
  fi
```
to:
```
 if [ "$m" != "GET" ]; then
    _debug data "$data"
    response="$(_post "$data" "$CF_Api/$ep" "" "$m")" | jj -u
  else
    response="$(_get "$CF_Api/$ep")" | jj -u
  fi
```

Just adding space to the grep fixes the one txt record case, sure, but there's still other cases that fail, such as removing the record.

Obviously using a random binary library is not a long term solution, but I'm not currently doing well at figuring out a bash way to uglify/minify json. A solution for parsing json without grep and cut would be preferable, but I'm not seeing one that wouldn't require more dependencies.

**Comment by mtis88** [comment]
Agree it would definitely be preferable to have a more robust way of parsing JSON vs grep etc.

**Comment by mtis88** [comment]
Another option could be to unprettify the JSON responses using:

`$(printf "%s\n" "$response" | tr -d [:space:])`

Then the grep changes I've made could be removed.

**Comment by mtis88** [comment]
To be clear on what the problem is here, Cloudflare are now pretty printing their JSON responses for some reason, breaking the checking of properties using grep. I think the best fix here is to un pretty print the response somehow, rather than changing each individual grep. Especially if Cloudflare change it back. I'm not sure how to do this cleanly though without jq or jj, something like that.

Any ideas for a pure bash solution?

**Comment by joecot** [comment]
For note I attempted just piping all the responses in the _cf_rest function through `jj -u`, and while that fixed the txt record lookup, it broke other parts of the script. Not all the greps are the same. Some are using `printf "%s"` while others are using `printf "%s\n"`. I'm not sure what all changed in the cloudflare response, but I don't think it is as simple as pretty print vs minified, and an example of the responses before would help track down the changes.

**Comment by joecot** [comment]
@mtis88  Sorry, been messing with this for too long. I did a clean install of acme.sh and added `response=$(echo $response | jj -u)` to _cf_rest  in dns_cf.sh, and I can confirm that all the requests are working.

While I'm a little uncomfortable with your approach of just removing all spaces from the response, it doesn't seem like there's anything in the JSON responses that would be fundamentally altered by doing so, and it doesn't require more dependencies. Maybe add the pull request back based off of development instead of master?

**Comment by mtis88** [comment]
@joecot I closed the PR for that exact reason - it removes spaces anywhere in the string. But as you say, it actually works in this case so I am actually using this solution myself for the time being, I just thought for wider use there would be a safer solution.

**Comment by joecot** [comment]
@mtis88 I just looked through my logs of responses that I minified using jj. I'm not seeing any spaces within the responses.

The only place I would expect spaces in the JSON are within the errors or messages properties, which the cloudflare integration does not appear to touch. So maybe we should debug the response before and after stripping spaces, but otherwise it doesn't appear like it will matter.

**Comment by mtis88** [comment]
@joecot I've created a branch from dev with the change. Happy to submit the PR if we think it's acceptable.

**Comment by joecot** [comment]
@mtis88 given the existing use of grep and such to parse JSON in this integration, I think your change to strip spaces is more than acceptable. A more robust JSON parsing would be better, but I'm assuming decisions were made to skip that to avoid more dependencies.

But I would suggest making it:

```
  if [ "$?" != "0" ]; then
    _err "error $ep"
    return 1
  fi
  _debug2 response "$response"
  response=$(echo $response | tr -d [:space:])
  _debug2 stripped_response "$response"
  return 0
```

Have it alter the response after the error checking, and debug2 output the response before and after you strip whitespace, so if there are error messages they're more readable.

**Comment by Aterfax** [comment]
Also having this error in OpenWRT latest build with the ACME scripts - edited the line to the first post and it fixed the issue.

**Comment by johannrichard** [comment]
Is there a reason why we can’t just check for zero or more whitespace in the grep expressions (there are other instances with the same problem)?

```bash
if ! printf "%s" "$response" | grep '\"success\":\s*true' >/dev/null; then
```

(not sure that’s portable but you get the idea)

PS: maybe someone over at CloudFlare was just debugging the API and added pretty-printing for that: :smile:

https://www.cloudflarestatus.com/incidents/jljrz1789325

**Comment by Neilpang** [comment]
@johannrichard 
Thanks for the  info.

I just don't trust `grep`.   it may not support regex on some platforms.
So, I just trim out all the space keys.

it's all fixed now.

Thanks.

**Comment by xdmitry** [comment]
@Neilpang could you please also update docker image neilpang/acme.sh with this fix?

**Comment by Neilpang** [comment]
@xdmitry  the scrip in docker container will upgrade itself tomorrow.

**Comment by xdmitry** [comment]
@Neilpang I'm still getting error message when trying to renew certificate with docker container. I'm using it as below

docker run -v /etc/acme:/acme.sh --rm neilpang/acme.sh --issue -d domain1 --challenge-alias domain2 --dns dns_cf --accountemail email

**Comment by BTSmolders** [comment]
@Neilpang Could you please fix the build pipeline for Docker (either in Docker Hub or Travis-CI). The latest image on Docker Hub is 3 months old and I also would like to use this fix.

**Comment by Neilpang** [comment]
@xdmitry  @BTSmolders 

it's updated. please try again.

Thanks.

**Comment by dkerr64** [comment]
@Neilpang can you please tag a new release (2.8.6?) so that this gets propagated ASAP.  My regular cron job failed overnight as it tried to renew a certificate that used Cloudflare DNS TXT verification.  Replacing my dns_cf.sh file with this fix solved the problem.  This feels like a widespread sev 1 issue for which fix should be send out ASAP.
Thanks.

**Comment by xdmitry** [comment]
@Neilpang it works now, thank you very much!

**Comment by Neilpang** [comment]
@dkerr64 

Here you go: 
https://github.com/acmesh-official/acme.sh/releases/tag/2.8.6
