### ISSUE TITLE
dns_me : invalid domain and Error add txt  when issuing a new certificate

### ISSUE THREAD

**Issue by gjjgat** [acmesh-official/acme.sh#2985]
I have been using acme.sh for over a year very successfully with 3 different domains and about 60 certificates in total. I use the DNS API mode with DNSMADEEASY.  I have the latest version (v2.8.6)

Steps to reproduce
------------------
Today I wanted to add two new certificates:  <subdomain.mydomain.com> and <subsubdomain02.subdomain.mydomain.com>.  I issued this command:

./.acme.sh/acme.sh --issue --dns dns_me -d subdomain.mydomain.com -d '*.subdomain.mydomain.com'

and I got this result:
[Tue Jun  9 18:44:57 AWST 2020] Adding txt value: 4hfy14fpGkXHZ_ssS6dolp7xBKpMC8YqTuGfyrcKSFU for domain:  _acme-challenge.subdomain.mydomain.com
[Tue Jun  9 18:45:01 AWST 2020] invalid domain
[Tue Jun  9 18:45:01 AWST 2020] Error add txt for domain:_acme-challenge.subdomain.mydomain.com

I can get the same result using staging with just one domain: 

 ./.acme.sh/acme.sh --staging --issue --dns dns_me -d subdomain.mydomain.com

I have examined issues: #2031, #2731, #2734, and #2916, and PR #2726 but am no wiser.  I can't tell if it has been fixed or is still a problem.

I tried using the suggested jq fix but that didn't work.

Can anyone clarify the situation?

Debug log
-----------------
Attached.

Thanks,

Bob
[issue.log](https://github.com/acmesh-official/acme.sh/files/4751719/issue.log)

**Comment by gjjgat** [comment]
As I said in my initial post, I did an upgrade first and am at v2.8.6.

In my initial post I attached a log with --debug 2

**Comment by ayn** [comment]
The [jq fix](https://github.com/acmesh-official/acme.sh/issues/2031#issuecomment-583234440) works for me. I'm never gonna enable auto upgrade ever again lol.

**Comment by wderuijter** [comment]
> The [jq fix](https://github.com/acmesh-official/acme.sh/issues/2031#issuecomment-583234440) works for me.

Yes, I needed this. Awesome @ayn.

**Comment by gplechuck** [comment]
Hello @gjjgat ,

I have just noticed the same issue - invalid domain when attempting to add the TXT record. The jq fix not working either, this fixes a problem that versions prior to 2.8.6 had with incorrect parsing of the domain id.

I have not had time to debug it yet, but in the debug output, have spotted the following which might give a clue . The debug output contains the API URLs the script contacts, eg url='https://api.dnsmadeeasy.com/V2.0/dns/managed/name?domainname=subdomain.mydomain.com'

The script seems to break the subdomains down one level at a time in order to find your root domain, but I believe it should stop at domainname=mydomain.com .

Instead its progressing as far as domainname=com 

When the script attempts to find the id of 'com' it will fail as its not a valid domain . 

Try this bash script - 

`#!/bin/bash                                                                                                                                                                                    

apikey='********'                                                                                                                                                   
secretkey='********'   

request_date=`date "+%a, %d %b %Y %T %Z"`
hmac=`echo -n "$request_date" | openssl dgst -sha1 -hmac "$secretkey"`

curl --location --request GET "https://api.dnsmadeeasy.com/V2.0/dns/managed/name?domainname=mydomain.com" \
        --header "content-type:application/json" \
        --header "x-dnsme-hmac:${hmac:9}" \
        --header "x-dnsme-apiKey:$apikey" \
        --header "x-dnsme-requestDate:$request_date" \
        --header "accept:application/json"
`

This should return some JSON output which includes the id of mydomain.com (substitute your own domain here of course).

Replace mydomain.com with com and you'll get a 404. I think this is whats happening, but have not verified.

Have you found a solution to this already by any chance? I notice on your own site that a new LetsEncrypt SSL cert was issued recently. 

Cheers

**Comment by gjjgat** [comment]
Very interesting, but It turned out that my problem was time sync.  The server that I was trying to get these certificates for didn't have time sync enabled and was far enough out for it to be an issue.  Once that was fixed acme worked immediately.

**Comment by gplechuck** [comment]
Indeed, this was the issue! Thanks. Jumped the gun there with a bad assumption based on the debug output. Had a chance to look at it just now, running the curl test on the actual machine with the problem returned the following error - 

{"error": ["Request sent with date header too far out of sync.  Difference in times is 62207, header value is 1597384213000"]}

Fixed after syncing time.

**Comment by gjjgat** [comment]
Glad it solved it.

**Comment by cirrusflyer** [comment]
I'm still getting this "invalid domain" issue with DNS Made Easy and time sync is not the issue.  Using the docker version.
