### ISSUE TITLE
Create CSR Error - possibly after upgrade to OpenBSD 7.0

### ISSUE THREAD

**Issue by mlindgren80** [acmesh-official/acme.sh#3833]
I have been using acme.sh succesfully for several years.  I believe after the upgrade to OpenBSD 7.0, I can no longer issue certificates.  OpenBSD introduced LibreSSL 3.4.1 with 7.0. 

Steps to reproduce
------------------
Issue certificates with OpenBSD 7.0

Debug log
-----------------
I have replaced my domain with example
```
[Mon Nov 29 10:35:35 MST 2021] ACME_KEY_CHANGE='https://acme-v02.api.letsencrypt.org/acme/key-change'
[Mon Nov 29 10:35:35 MST 2021] ACME_NEW_AUTHZ
[Mon Nov 29 10:35:35 MST 2021] ACME_NEW_ORDER='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Mon Nov 29 10:35:35 MST 2021] ACME_NEW_ACCOUNT='https://acme-v02.api.letsencrypt.org/acme/new-acct'
[Mon Nov 29 10:35:35 MST 2021] ACME_REVOKE_CERT='https://acme-v02.api.letsencrypt.org/acme/revoke-cert'
[Mon Nov 29 10:35:35 MST 2021] ACME_AGREEMENT='https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf'
[Mon Nov 29 10:35:35 MST 2021] ACME_NEW_NONCE='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Mon Nov 29 10:35:36 MST 2021] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Mon Nov 29 10:35:36 MST 2021] _on_before_issue
[Mon Nov 29 10:35:36 MST 2021] _chk_main_domain='vpn.example.com'
[Mon Nov 29 10:35:36 MST 2021] _chk_alt_domains
[Mon Nov 29 10:35:36 MST 2021] 'dns_cf' does not contain 'no'
[Mon Nov 29 10:35:36 MST 2021] Le_LocalAddress
[Mon Nov 29 10:35:36 MST 2021] d='vpn.example.com'
[Mon Nov 29 10:35:36 MST 2021] Check for domain='vpn.example.com'
[Mon Nov 29 10:35:36 MST 2021] _currentRoot='dns_cf'
[Mon Nov 29 10:35:36 MST 2021] d
[Mon Nov 29 10:35:36 MST 2021] 'dns_cf' does not contain 'apache'
[Mon Nov 29 10:35:36 MST 2021] _saved_account_key_hash='MDJMPBJebkzRL4vGPvYO7eSa1RpjVuNfGEBU63V4pFY='
[Mon Nov 29 10:35:36 MST 2021] _saved_account_key_hash is not changed, skip register account.
[Mon Nov 29 10:35:36 MST 2021] Read key length:ec-256
[Mon Nov 29 10:35:36 MST 2021] _createcsr
[Mon Nov 29 10:35:36 MST 2021] domain='vpn.example.com'
[Mon Nov 29 10:35:36 MST 2021] domainlist
[Mon Nov 29 10:35:36 MST 2021] csrkey='/root/.acme.sh/vpn.example.com_ecc/vpn.example.com.key'
[Mon Nov 29 10:35:36 MST 2021] csr='/root/.acme.sh/vpn.example.com_ecc/vpn.example.com.csr'
[Mon Nov 29 10:35:36 MST 2021] csrconf='/root/.acme.sh/vpn.example.com_ecc/vpn.example.com.csr.conf'
[Mon Nov 29 10:35:36 MST 2021] Single domain='vpn.example.com'
[Mon Nov 29 10:35:36 MST 2021] _is_idn_d='vpn.example.com'
[Mon Nov 29 10:35:36 MST 2021] _idn_temp
[Mon Nov 29 10:35:36 MST 2021] _is_idn_d='vpn.example.com'
[Mon Nov 29 10:35:36 MST 2021] _idn_temp
[Mon Nov 29 10:35:36 MST 2021] _csr_cn='vpn.example.com'
Error Loading request extension section v3_req
15736267479008:error:22FFF076:X509 V3 routines:func(4095):reason(118):/usr/src/lib/libcrypto/x509/x509_alt.c:568:value=vpn.example.com
15736267479008:error:22FFF080:X509 V3 routines:func(4095):reason(128):/usr/src/lib/libcrypto/x509/x509_conf.c:100:name=subjectAltName, value=IP:vpn.example.com
[Mon Nov 29 10:35:36 MST 2021] Create CSR error.
[Mon Nov 29 10:35:36 MST 2021] pid
[Mon Nov 29 10:35:36 MST 2021] No need to restore nginx, skip.
[Mon Nov 29 10:35:36 MST 2021] _clearupdns
[Mon Nov 29 10:35:36 MST 2021] dns_entries
[Mon Nov 29 10:35:36 MST 2021] skip dns.
[Mon Nov 29 10:35:36 MST 2021] _on_issue_err
[Mon Nov 29 10:35:36 MST 2021] Please add '--debug' or '--log' to check more details.
[Mon Nov 29 10:35:36 MST 2021] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Mon Nov 29 10:35:36 MST 2021] _chk_vlist
[Mon Nov 29 10:35:36 MST 2021] 'dns_cf' does not contain 'dns'
[Mon Nov 29 10:35:36 MST 2021] socat doesn't exist.
[Mon Nov 29 10:35:36 MST 2021] Diagnosis versions:
openssl:openssl
LibreSSL 3.4.1
```

**Comment by Neilpang** [comment]
please use `--debug 2`

**Comment by mlindgren80** [comment]
This is the full output with --debug 2.  I don't believe it adds any additional details 

```
[Tue Nov 30 14:13:19 MST 2021] Lets find script dir.
[Tue Nov 30 14:13:19 MST 2021] _SCRIPT_='/root/.acme.sh/acme.sh'
[Tue Nov 30 14:13:19 MST 2021] _script='/root/.acme.sh/acme.sh'
[Tue Nov 30 14:13:19 MST 2021] _script_home='/root/.acme.sh'
[Tue Nov 30 14:13:19 MST 2021] Using config home:/root/.acme.sh
[Tue Nov 30 14:13:19 MST 2021] LE_WORKING_DIR='/root/.acme.sh'
https://github.com/acmesh-official/acme.sh
v3.0.2
[Tue Nov 30 14:13:19 MST 2021] Running cmd: cron
[Tue Nov 30 14:13:19 MST 2021] Using config home:/root/.acme.sh
[Tue Nov 30 14:13:19 MST 2021] default_acme_server='https://acme-v02.api.letsencrypt.org/directory'
[Tue Nov 30 14:13:19 MST 2021] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Tue Nov 30 14:13:19 MST 2021] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
[Tue Nov 30 14:13:19 MST 2021] _ACME_SERVER_PATH='directory'
[Tue Nov 30 14:13:19 MST 2021] ===Starting cron===
[Tue Nov 30 14:13:19 MST 2021] Using config home:/root/.acme.sh
[Tue Nov 30 14:13:19 MST 2021] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Tue Nov 30 14:13:19 MST 2021] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
[Tue Nov 30 14:13:19 MST 2021] _ACME_SERVER_PATH='directory'
[Tue Nov 30 14:13:19 MST 2021] Retrying GET
[Tue Nov 30 14:13:19 MST 2021] GET
[Tue Nov 30 14:13:19 MST 2021] url='https://api.github.com/repos/acmesh-official/acme.sh/git/refs/heads/master'
[Tue Nov 30 14:13:19 MST 2021] timeout=
[Tue Nov 30 14:13:19 MST 2021] displayError='1'
[Tue Nov 30 14:13:19 MST 2021] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.CBic1ajgMV '
[Tue Nov 30 14:13:20 MST 2021] ret='0'
[Tue Nov 30 14:13:20 MST 2021] _hcode='0'
[Tue Nov 30 14:13:20 MST 2021] Installing from online archive.
[Tue Nov 30 14:13:20 MST 2021] Downloading https://github.com/acmesh-official/acme.sh/archive/master.tar.gz
[Tue Nov 30 14:13:20 MST 2021] Retrying GET
[Tue Nov 30 14:13:20 MST 2021] GET
[Tue Nov 30 14:13:20 MST 2021] url='https://github.com/acmesh-official/acme.sh/archive/master.tar.gz'
[Tue Nov 30 14:13:20 MST 2021] timeout=
[Tue Nov 30 14:13:20 MST 2021] displayError='1'
[Tue Nov 30 14:13:20 MST 2021] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.Fu7ertKQTz '
[Tue Nov 30 14:13:21 MST 2021] ret='0'
[Tue Nov 30 14:13:21 MST 2021] _hcode='0'
[Tue Nov 30 14:13:21 MST 2021] Extracting master.tar.gz
[Tue Nov 30 14:13:21 MST 2021] Installing to /root/.acme.sh
[Tue Nov 30 14:13:21 MST 2021] Installed to /root/.acme.sh/acme.sh
[Tue Nov 30 14:13:21 MST 2021] OK
[Tue Nov 30 14:13:22 MST 2021] Install success!
[Tue Nov 30 14:13:22 MST 2021] Using config home:/root/.acme.sh
[Tue Nov 30 14:13:22 MST 2021] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Tue Nov 30 14:13:22 MST 2021] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
[Tue Nov 30 14:13:22 MST 2021] _ACME_SERVER_PATH='directory'
[Tue Nov 30 14:13:22 MST 2021] Retrying GET
[Tue Nov 30 14:13:22 MST 2021] GET
[Tue Nov 30 14:13:22 MST 2021] url='https://api.github.com/repos/acmesh-official/acme.sh/git/refs/heads/master'
[Tue Nov 30 14:13:22 MST 2021] timeout=
[Tue Nov 30 14:13:22 MST 2021] displayError='1'
[Tue Nov 30 14:13:22 MST 2021] Http already initialized.
[Tue Nov 30 14:13:22 MST 2021] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.Fu7ertKQTz '
[Tue Nov 30 14:13:22 MST 2021] ret='0'
[Tue Nov 30 14:13:22 MST 2021] _hcode='0'
[Tue Nov 30 14:13:22 MST 2021] Upgrade success!
[Tue Nov 30 14:13:22 MST 2021] Using config home:/root/.acme.sh
[Tue Nov 30 14:13:22 MST 2021] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Tue Nov 30 14:13:22 MST 2021] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
[Tue Nov 30 14:13:22 MST 2021] _ACME_SERVER_PATH='directory'
[Tue Nov 30 14:13:22 MST 2021] Auto upgraded to: 3.0.2
[Tue Nov 30 14:13:22 MST 2021] Using config home:/root/.acme.sh
[Tue Nov 30 14:13:22 MST 2021] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Tue Nov 30 14:13:22 MST 2021] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
[Tue Nov 30 14:13:22 MST 2021] _ACME_SERVER_PATH='directory'
[Tue Nov 30 14:13:22 MST 2021] _stopRenewOnError
[Tue Nov 30 14:13:22 MST 2021] _set_level='2'
[Tue Nov 30 14:13:22 MST 2021] di='/root/.acme.sh/vpn.example.com/'
[Tue Nov 30 14:13:22 MST 2021] d='vpn.example.com'
[Tue Nov 30 14:13:22 MST 2021] Using config home:/root/.acme.sh
[Tue Nov 30 14:13:22 MST 2021] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Tue Nov 30 14:13:23 MST 2021] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
[Tue Nov 30 14:13:23 MST 2021] _ACME_SERVER_PATH='directory'
[Tue Nov 30 14:13:23 MST 2021] DOMAIN_PATH='/root/.acme.sh/vpn.example.com'
[Tue Nov 30 14:13:23 MST 2021] Renew: 'vpn.example.com'
[Tue Nov 30 14:13:23 MST 2021] Le_API='https://acme-v02.api.letsencrypt.org/directory'
[Tue Nov 30 14:13:23 MST 2021] Using config home:/root/.acme.sh
[Tue Nov 30 14:13:23 MST 2021] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Tue Nov 30 14:13:23 MST 2021] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
[Tue Nov 30 14:13:23 MST 2021] _ACME_SERVER_PATH='directory'
[Tue Nov 30 14:13:23 MST 2021] Skip invalid cert for: vpn.example.com
[Tue Nov 30 14:13:23 MST 2021] Return code: 2
[Tue Nov 30 14:13:23 MST 2021] Skipped vpn.example.com
[Tue Nov 30 14:13:23 MST 2021] di='/root/.acme.sh/vpn.example.com_ecc/'
[Tue Nov 30 14:13:23 MST 2021] d='vpn.example.com_ecc'
[Tue Nov 30 14:13:23 MST 2021] Using config home:/root/.acme.sh
[Tue Nov 30 14:13:23 MST 2021] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Tue Nov 30 14:13:23 MST 2021] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
[Tue Nov 30 14:13:23 MST 2021] _ACME_SERVER_PATH='directory'
[Tue Nov 30 14:13:23 MST 2021] DOMAIN_PATH='/root/.acme.sh/vpn.example.com_ecc'
[Tue Nov 30 14:13:23 MST 2021] Renew: 'vpn.example.com'
[Tue Nov 30 14:13:23 MST 2021] Le_API='https://acme-v02.api.letsencrypt.org/directory'
[Tue Nov 30 14:13:23 MST 2021] Using config home:/root/.acme.sh
[Tue Nov 30 14:13:23 MST 2021] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Tue Nov 30 14:13:23 MST 2021] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
[Tue Nov 30 14:13:23 MST 2021] _ACME_SERVER_PATH='directory'
[Tue Nov 30 14:13:23 MST 2021] _main_domain='vpn.example.com'
[Tue Nov 30 14:13:23 MST 2021] _alt_domains='no'
[Tue Nov 30 14:13:23 MST 2021] 'dns_cf' does not contain 'dns'
[Tue Nov 30 14:13:23 MST 2021] 'dns_cf' does not contain 'dns'
[Tue Nov 30 14:13:23 MST 2021] Le_NextRenewTime='1637906433'
[Tue Nov 30 14:13:23 MST 2021] Using ACME_DIRECTORY: https://acme-v02.api.letsencrypt.org/directory
[Tue Nov 30 14:13:23 MST 2021] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[Tue Nov 30 14:13:23 MST 2021] Retrying GET
[Tue Nov 30 14:13:23 MST 2021] GET
[Tue Nov 30 14:13:23 MST 2021] url='https://acme-v02.api.letsencrypt.org/directory'
[Tue Nov 30 14:13:23 MST 2021] timeout=
[Tue Nov 30 14:13:23 MST 2021] displayError='1'
[Tue Nov 30 14:13:23 MST 2021] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.9HItXNS4Ay '
[Tue Nov 30 14:13:24 MST 2021] ret='0'
[Tue Nov 30 14:13:24 MST 2021] _hcode='0'
[Tue Nov 30 14:13:24 MST 2021] response='{
  "czApF7PuiKY": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}'
[Tue Nov 30 14:13:24 MST 2021] ACME_KEY_CHANGE='https://acme-v02.api.letsencrypt.org/acme/key-change'
[Tue Nov 30 14:13:24 MST 2021] ACME_NEW_AUTHZ
[Tue Nov 30 14:13:24 MST 2021] ACME_NEW_ORDER='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Tue Nov 30 14:13:24 MST 2021] ACME_NEW_ACCOUNT='https://acme-v02.api.letsencrypt.org/acme/new-acct'
[Tue Nov 30 14:13:24 MST 2021] ACME_REVOKE_CERT='https://acme-v02.api.letsencrypt.org/acme/revoke-cert'
[Tue Nov 30 14:13:24 MST 2021] ACME_AGREEMENT='https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf'
[Tue Nov 30 14:13:24 MST 2021] ACME_NEW_NONCE='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Tue Nov 30 14:13:24 MST 2021] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Tue Nov 30 14:13:24 MST 2021] _on_before_issue
[Tue Nov 30 14:13:24 MST 2021] _chk_main_domain='vpn.example.com'
[Tue Nov 30 14:13:24 MST 2021] _chk_alt_domains
[Tue Nov 30 14:13:24 MST 2021] 'dns_cf' does not contain 'no'
[Tue Nov 30 14:13:24 MST 2021] Le_LocalAddress
[Tue Nov 30 14:13:24 MST 2021] d='vpn.example.com'
[Tue Nov 30 14:13:24 MST 2021] Check for domain='vpn.example.com'
[Tue Nov 30 14:13:24 MST 2021] _currentRoot='dns_cf'
[Tue Nov 30 14:13:25 MST 2021] d
[Tue Nov 30 14:13:25 MST 2021] 'dns_cf' does not contain 'apache'
[Tue Nov 30 14:13:25 MST 2021] _saved_account_key_hash='MDJMPBJebkzRL4vGPvYO7eSa1RpjVuNfGEBU63V4pFY='
[Tue Nov 30 14:13:25 MST 2021] _saved_account_key_hash is not changed, skip register account.
[Tue Nov 30 14:13:25 MST 2021] Read key length:ec-256
[Tue Nov 30 14:13:25 MST 2021] _createcsr
[Tue Nov 30 14:13:25 MST 2021] domain='vpn.example.com'
[Tue Nov 30 14:13:25 MST 2021] domainlist
[Tue Nov 30 14:13:25 MST 2021] csrkey='/root/.acme.sh/vpn.example.com_ecc/vpn.example.com.key'
[Tue Nov 30 14:13:25 MST 2021] csr='/root/.acme.sh/vpn.example.com_ecc/vpn.example.com.csr'
[Tue Nov 30 14:13:25 MST 2021] csrconf='/root/.acme.sh/vpn.example.com_ecc/vpn.example.com.csr.conf'
[Tue Nov 30 14:13:25 MST 2021] Single domain='vpn.example.com'
[Tue Nov 30 14:13:25 MST 2021] _is_idn_d='vpn.example.com'
[Tue Nov 30 14:13:25 MST 2021] _idn_temp
[Tue Nov 30 14:13:25 MST 2021] _is_idn_d='vpn.example.com'
[Tue Nov 30 14:13:25 MST 2021] _idn_temp
[Tue Nov 30 14:13:25 MST 2021] _csr_cn='vpn.example.com'
Error Loading request extension section v3_req
15689196152800:error:22FFF076:X509 V3 routines:func(4095):reason(118):/usr/src/lib/libcrypto/x509/x509_alt.c:568:value=vpn.example.com
15689196152800:error:22FFF080:X509 V3 routines:func(4095):reason(128):/usr/src/lib/libcrypto/x509/x509_conf.c:100:name=subjectAltName, value=IP:vpn.example.com
[Tue Nov 30 14:13:25 MST 2021] Create CSR error.
[Tue Nov 30 14:13:25 MST 2021] pid
[Tue Nov 30 14:13:25 MST 2021] No need to restore nginx, skip.
[Tue Nov 30 14:13:25 MST 2021] _clearupdns
[Tue Nov 30 14:13:25 MST 2021] dns_entries
[Tue Nov 30 14:13:25 MST 2021] skip dns.
[Tue Nov 30 14:13:25 MST 2021] _on_issue_err
[Tue Nov 30 14:13:25 MST 2021] Please add '--debug' or '--log' to check more details.
[Tue Nov 30 14:13:25 MST 2021] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Tue Nov 30 14:13:25 MST 2021] _chk_vlist
[Tue Nov 30 14:13:25 MST 2021] 'dns_cf' does not contain 'dns'
[Tue Nov 30 14:13:25 MST 2021] socat doesn't exist.
[Tue Nov 30 14:13:25 MST 2021] Diagnosis versions:
openssl:openssl
LibreSSL 3.4.1
apache:
apache doesn't exist.
nginx:
nginx doesn't exist.
socat:
[Tue Nov 30 14:13:25 MST 2021] Return code: 1
[Tue Nov 30 14:13:25 MST 2021] Error renew vpn.example.com_ecc.
[Tue Nov 30 14:13:25 MST 2021] _error_level='1'
[Tue Nov 30 14:13:25 MST 2021] _set_level='2'
[Tue Nov 30 14:13:25 MST 2021] Sending via: pushover
[Tue Nov 30 14:13:25 MST 2021] Found /root/.acme.sh/notify/pushover.sh for pushover
[Tue Nov 30 14:13:25 MST 2021] _statusCode='1'
[Tue Nov 30 14:13:26 MST 2021] _URGLY_PRINTF
[Tue Nov 30 14:13:26 MST 2021] xargs
[Tue Nov 30 14:13:26 MST 2021] _URGLY_PRINTF
[Tue Nov 30 14:13:26 MST 2021] xargs
[Tue Nov 30 14:13:26 MST 2021] Retrying post
[Tue Nov 30 14:13:26 MST 2021] POST
[Tue Nov 30 14:13:26 MST 2021] _post_url='https://api.pushover.net/1/messages.json'
[Tue Nov 30 14:13:26 MST 2021] body='{"token": "app14j1zv4d8gu5s3zxxvq3oygv2qo","user": "u6bw2ebmzwp8nhpc9i85m5bafgigam","title": "*Renew Error Skipped*\n","message": "*Error certs:\n    vpn.example.com_ecc\n\nSkipped certs:\n    vpn.example.com\n\n*\n","sound": "", "device": "", "priority": ""}'
[Tue Nov 30 14:13:26 MST 2021] _postContentType
[Tue Nov 30 14:13:26 MST 2021] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.RJHCyaVxg0 '
[Tue Nov 30 14:13:26 MST 2021] _ret='0'
[Tue Nov 30 14:13:26 MST 2021] _hcode='0'
[Tue Nov 30 14:13:26 MST 2021] PUSHOVER send success.
[Tue Nov 30 14:13:26 MST 2021] pushover Success
[Tue Nov 30 14:13:27 MST 2021] ===End cron===

```

**Comment by Neilpang** [comment]
I don't have a OpenBSD vm, I tried it on my openBSD 6.9, it works well.

**Comment by mlindgren80** [comment]
Correct, it was working fine in 6.9 and for several releases before that.  Only. stopped working after I upgraded the box to 7.0.

**Comment by Neilpang** [comment]
fixed.  please try the latest dev branch:

```
acme.sh  --upgrade -b dev
```

**Comment by mlindgren80** [comment]
it is indeed working now, thank you!

**Comment by c0dev0id** [comment]
I hit the same issue and can confirm that it works on OpenBSD 7.0 now.

**Comment by hokascha** [comment]
I run into the same issue on Ubuntu 18.04. Upgrading to the latest dev branch did not solve the issue. Here's the debug output:
```
# acme.sh --renew-all --debug 2
[Mi 3. Aug 10:32:48 CEST 2022] Lets find script dir.
[Mi 3. Aug 10:32:48 CEST 2022] _SCRIPT_='/root/.acme.sh/acme.sh'
[Mi 3. Aug 10:32:48 CEST 2022] _script='/root/.acme.sh/acme.sh'
[Mi 3. Aug 10:32:48 CEST 2022] _script_home='/root/.acme.sh'
[Mi 3. Aug 10:32:48 CEST 2022] Using config home:/root/.acme.sh
[Mi 3. Aug 10:32:48 CEST 2022] LE_WORKING_DIR='/root/.acme.sh'
https://github.com/acmesh-official/acme.sh
v3.0.5
[Mi 3. Aug 10:32:48 CEST 2022] Running cmd: renewAll
[Mi 3. Aug 10:32:48 CEST 2022] Using config home:/root/.acme.sh
[Mi 3. Aug 10:32:48 CEST 2022] default_acme_server='https://acme-v02.api.letsencrypt.org/directory'
[Mi 3. Aug 10:32:48 CEST 2022] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Mi 3. Aug 10:32:48 CEST 2022] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
[Mi 3. Aug 10:32:48 CEST 2022] _ACME_SERVER_PATH='directory'
[Mi 3. Aug 10:32:48 CEST 2022] _stopRenewOnError
[Mi 3. Aug 10:32:48 CEST 2022] _server
[Mi 3. Aug 10:32:48 CEST 2022] _set_level='2'
[Mi 3. Aug 10:32:48 CEST 2022] di='/root/.acme.sh/*.kandidaten-befragung.de/'
[Mi 3. Aug 10:32:48 CEST 2022] d='*.kandidaten-befragung.de'
[Mi 3. Aug 10:32:48 CEST 2022] _renewServer
[Mi 3. Aug 10:32:48 CEST 2022] Using config home:/root/.acme.sh
[Mi 3. Aug 10:32:48 CEST 2022] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Mi 3. Aug 10:32:48 CEST 2022] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
[Mi 3. Aug 10:32:48 CEST 2022] _ACME_SERVER_PATH='directory'
[Mi 3. Aug 10:32:48 CEST 2022] DOMAIN_PATH='/root/.acme.sh/*.kandidaten-befragung.de'
[Mi 3. Aug 10:32:48 CEST 2022] Renew: '*.kandidaten-befragung.de'
[Mi 3. Aug 10:32:48 CEST 2022] Le_API='https://acme-v02.api.letsencrypt.org/directory'
[Mi 3. Aug 10:32:48 CEST 2022] Renew to Le_API=https://acme-v02.api.letsencrypt.org/directory
[Mi 3. Aug 10:32:48 CEST 2022] initpath again.
[Mi 3. Aug 10:32:48 CEST 2022] Using config home:/root/.acme.sh
[Mi 3. Aug 10:32:48 CEST 2022] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Mi 3. Aug 10:32:48 CEST 2022] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
[Mi 3. Aug 10:32:48 CEST 2022] _ACME_SERVER_PATH='directory'
[Mi 3. Aug 10:32:48 CEST 2022] Skip, Next renewal time is: 2022-08-22T11:53:55Z
[Mi 3. Aug 10:32:48 CEST 2022] Add '--force' to force to renew.
[Mi 3. Aug 10:32:48 CEST 2022] Return code: 2
[Mi 3. Aug 10:32:48 CEST 2022] Skipped *.kandidaten-befragung.de
[Mi 3. Aug 10:32:48 CEST 2022] di='/root/.acme.sh/*.strausberg-design.de/'
[Mi 3. Aug 10:32:48 CEST 2022] d='*.strausberg-design.de'
[Mi 3. Aug 10:32:48 CEST 2022] _renewServer
[Mi 3. Aug 10:32:48 CEST 2022] Using config home:/root/.acme.sh
[Mi 3. Aug 10:32:48 CEST 2022] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Mi 3. Aug 10:32:48 CEST 2022] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
[Mi 3. Aug 10:32:48 CEST 2022] _ACME_SERVER_PATH='directory'
[Mi 3. Aug 10:32:48 CEST 2022] DOMAIN_PATH='/root/.acme.sh/*.strausberg-design.de'
[Mi 3. Aug 10:32:48 CEST 2022] Renew: '*.strausberg-design.de'
[Mi 3. Aug 10:32:48 CEST 2022] Le_API='https://acme-v02.api.letsencrypt.org/directory'
[Mi 3. Aug 10:32:48 CEST 2022] Renew to Le_API=https://acme-v02.api.letsencrypt.org/directory
[Mi 3. Aug 10:32:48 CEST 2022] initpath again.
[Mi 3. Aug 10:32:48 CEST 2022] Using config home:/root/.acme.sh
[Mi 3. Aug 10:32:48 CEST 2022] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Mi 3. Aug 10:32:48 CEST 2022] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
[Mi 3. Aug 10:32:48 CEST 2022] _ACME_SERVER_PATH='directory'
[Mi 3. Aug 10:32:48 CEST 2022] _main_domain='*.strausberg-design.de'
[Mi 3. Aug 10:32:48 CEST 2022] _alt_domains='no'
[Mi 3. Aug 10:32:48 CEST 2022] 'dns_doapi' does not contain 'dns'
[Mi 3. Aug 10:32:48 CEST 2022] 'dns_doapi' does not contain 'dns'
[Mi 3. Aug 10:32:48 CEST 2022] Le_NextRenewTime='1659391711'
[Mi 3. Aug 10:32:48 CEST 2022] Using ACME_DIRECTORY: https://acme-v02.api.letsencrypt.org/directory
[Mi 3. Aug 10:32:48 CEST 2022] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[Mi 3. Aug 10:32:48 CEST 2022] GET
[Mi 3. Aug 10:32:48 CEST 2022] url='https://acme-v02.api.letsencrypt.org/directory'
[Mi 3. Aug 10:32:48 CEST 2022] timeout=
[Mi 3. Aug 10:32:48 CEST 2022] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.AeCyxZmXx2  -g '
[Mi 3. Aug 10:32:48 CEST 2022] ret='0'
[Mi 3. Aug 10:32:48 CEST 2022] response='{
  "MAETUVzWpsU": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}'
[Mi 3. Aug 10:32:48 CEST 2022] ACME_KEY_CHANGE='https://acme-v02.api.letsencrypt.org/acme/key-change'
[Mi 3. Aug 10:32:48 CEST 2022] ACME_NEW_AUTHZ
[Mi 3. Aug 10:32:48 CEST 2022] ACME_NEW_ORDER='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Mi 3. Aug 10:32:48 CEST 2022] ACME_NEW_ACCOUNT='https://acme-v02.api.letsencrypt.org/acme/new-acct'
[Mi 3. Aug 10:32:48 CEST 2022] ACME_REVOKE_CERT='https://acme-v02.api.letsencrypt.org/acme/revoke-cert'
[Mi 3. Aug 10:32:48 CEST 2022] ACME_AGREEMENT='https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf'
[Mi 3. Aug 10:32:48 CEST 2022] ACME_NEW_NONCE='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Mi 3. Aug 10:32:49 CEST 2022] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Mi 3. Aug 10:32:49 CEST 2022] _on_before_issue
[Mi 3. Aug 10:32:49 CEST 2022] _chk_main_domain='*.strausberg-design.de'
[Mi 3. Aug 10:32:49 CEST 2022] _chk_alt_domains
[Mi 3. Aug 10:32:49 CEST 2022] 'dns_doapi' does not contain 'no'
[Mi 3. Aug 10:32:49 CEST 2022] Le_LocalAddress
[Mi 3. Aug 10:32:49 CEST 2022] d='*.strausberg-design.de'
[Mi 3. Aug 10:32:49 CEST 2022] Check for domain='*.strausberg-design.de'
[Mi 3. Aug 10:32:49 CEST 2022] _currentRoot='dns_doapi'
[Mi 3. Aug 10:32:49 CEST 2022] d
[Mi 3. Aug 10:32:49 CEST 2022] 'dns_doapi' does not contain 'apache'
[Mi 3. Aug 10:32:49 CEST 2022] _saved_account_key_hash='6qZ671aF6Vu3UipdB9MR84aCYRD3Gx6s1ScU2RoCOLQ='
[Mi 3. Aug 10:32:49 CEST 2022] _saved_account_key_hash is not changed, skip register account.
[Mi 3. Aug 10:32:49 CEST 2022] Read key length:2048
[Mi 3. Aug 10:32:49 CEST 2022] _createcsr
[Mi 3. Aug 10:32:49 CEST 2022] domain='*.strausberg-design.de'
[Mi 3. Aug 10:32:49 CEST 2022] domainlist
[Mi 3. Aug 10:32:49 CEST 2022] csrkey='/root/.acme.sh/*.strausberg-design.de/*.strausberg-design.de.key'
[Mi 3. Aug 10:32:49 CEST 2022] csr='/root/.acme.sh/*.strausberg-design.de/*.strausberg-design.de.csr'
[Mi 3. Aug 10:32:49 CEST 2022] csrconf='/root/.acme.sh/*.strausberg-design.de/*.strausberg-design.de.csr.conf'
[Mi 3. Aug 10:32:49 CEST 2022] Single domain='*.strausberg-design.de'
[Mi 3. Aug 10:32:49 CEST 2022] seg='--'
[Mi 3. Aug 10:32:49 CEST 2022] _is_idn_d='*.strausberg-design.de'
[Mi 3. Aug 10:32:49 CEST 2022] _idn_temp='srausbergdesignde'
[Mi 3. Aug 10:32:49 CEST 2022] Please install idn to process IDN names.
[Mi 3. Aug 10:32:49 CEST 2022] _is_idn_d='*.strausberg-design.de'
[Mi 3. Aug 10:32:49 CEST 2022] _idn_temp='srausbergdesignde'
[Mi 3. Aug 10:32:49 CEST 2022] Please install idn to process IDN names.
[Mi 3. Aug 10:32:49 CEST 2022] _csr_cn
Error Loading request extension section v3_req
140070915150272:error:2206D06D:X509 V3 routines:X509V3_parse_list:invalid null value:../crypto/x509v3/v3_utl.c:379:
140070915150272:error:22097069:X509 V3 routines:do_ext_nconf:invalid extension string:../crypto/x509v3/v3_conf.c:93:name=subjectAltName,section=DNS:
140070915150272:error:22098080:X509 V3 routines:X509V3_EXT_nconf:error in extension:../crypto/x509v3/v3_conf.c:47:name=subjectAltName, value=DNS:
[Mi 3. Aug 10:32:49 CEST 2022] Create CSR error.
[Mi 3. Aug 10:32:49 CEST 2022] pid
[Mi 3. Aug 10:32:49 CEST 2022] No need to restore nginx, skip.
[Mi 3. Aug 10:32:49 CEST 2022] _clearupdns
[Mi 3. Aug 10:32:49 CEST 2022] dns_entries
[Mi 3. Aug 10:32:49 CEST 2022] skip dns.
[Mi 3. Aug 10:32:49 CEST 2022] _on_issue_err
[Mi 3. Aug 10:32:49 CEST 2022] Please add '--debug' or '--log' to check more details.
[Mi 3. Aug 10:32:49 CEST 2022] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Mi 3. Aug 10:32:49 CEST 2022] _chk_vlist
[Mi 3. Aug 10:32:49 CEST 2022] 'dns_doapi' does not contain 'dns'
[Mi 3. Aug 10:32:49 CEST 2022] socat doesn't exist.
[Mi 3. Aug 10:32:49 CEST 2022] Diagnosis versions: 
openssl:openssl
OpenSSL 1.1.1  11 Sep 2018
apache:
apache doesn't exist.
nginx:
nginx version: nginx/1.14.0 (Ubuntu)
built with OpenSSL 1.1.1  11 Sep 2018
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fdebug-prefix-map=/build/nginx-KgqPmI/nginx-1.14.0=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fPIC' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --modules-path=/usr/lib/nginx/modules --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-debug --with-pcre-jit --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_v2_module --with-http_dav_module --with-http_slice_module --with-threads --with-http_addition_module --with-http_geoip_module=dynamic --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module=dynamic --with-http_sub_module --with-http_xslt_module=dynamic --with-stream=dynamic --with-stream_ssl_module --with-mail=dynamic --with-mail_ssl_module
socat:
[Mi 3. Aug 10:32:49 CEST 2022] Return code: 1
[Mi 3. Aug 10:32:49 CEST 2022] Error renew *.strausberg-design.de.
[Mi 3. Aug 10:32:49 CEST 2022] _error_level='1'
[Mi 3. Aug 10:32:49 CEST 2022] _set_level='2'
[Mi 3. Aug 10:32:49 CEST 2022] Sending via: mail
[Mi 3. Aug 10:32:49 CEST 2022] Found /root/.acme.sh/notify/mail.sh for mail
[Mi 3. Aug 10:32:49 CEST 2022] _subject='Renew Error Skipped'
[Mi 3. Aug 10:32:49 CEST 2022] _content='Error certs:
    *.strausberg-design.de

Skipped certs:
    *.kandidaten-befragung.de

'
[Mi 3. Aug 10:32:49 CEST 2022] _statusCode='1'
[Mi 3. Aug 10:32:49 CEST 2022] mail send success.
[Mi 3. Aug 10:32:49 CEST 2022] mail Success
```

**Comment by Neilpang** [comment]
fixed.  please try again with the latest `dev` branch

```
acme.sh --upgrade -b dev
```

**Comment by hokascha** [comment]
Same issue after upgrading:

```
# acme.sh  --upgrade -b dev
[Do 4. Aug 10:35:53 CEST 2022] Installing from online archive.
[Do 4. Aug 10:35:53 CEST 2022] Downloading https://github.com/acmesh-official/acme.sh/archive/dev.tar.gz
[Do 4. Aug 10:35:54 CEST 2022] Extracting dev.tar.gz
[Do 4. Aug 10:35:54 CEST 2022] It is recommended to install socat first.
[Do 4. Aug 10:35:54 CEST 2022] We use socat for standalone server if you use standalone mode.
[Do 4. Aug 10:35:54 CEST 2022] If you don't use standalone mode, just ignore this warning.
[Do 4. Aug 10:35:54 CEST 2022] Installing to /root/.acme.sh
[Do 4. Aug 10:35:54 CEST 2022] Installed to /root/.acme.sh/acme.sh
[Do 4. Aug 10:35:54 CEST 2022] Good, bash is found, so change the shebang to use bash as preferred.
[Do 4. Aug 10:35:54 CEST 2022] OK
[Do 4. Aug 10:35:54 CEST 2022] Install success!
[Do 4. Aug 10:35:54 CEST 2022] Upgrade success!
root@mail ~ # acme.sh --renew-all --debug 2
[Do 4. Aug 10:36:01 CEST 2022] Lets find script dir.
[Do 4. Aug 10:36:01 CEST 2022] _SCRIPT_='/root/.acme.sh/acme.sh'
[Do 4. Aug 10:36:01 CEST 2022] _script='/root/.acme.sh/acme.sh'
[Do 4. Aug 10:36:01 CEST 2022] _script_home='/root/.acme.sh'
[Do 4. Aug 10:36:01 CEST 2022] Using config home:/root/.acme.sh
[Do 4. Aug 10:36:01 CEST 2022] LE_WORKING_DIR='/root/.acme.sh'
https://github.com/acmesh-official/acme.sh
v3.0.5
[Do 4. Aug 10:36:01 CEST 2022] Running cmd: renewAll
[Do 4. Aug 10:36:01 CEST 2022] Using config home:/root/.acme.sh
[Do 4. Aug 10:36:01 CEST 2022] default_acme_server='https://acme-v02.api.letsencrypt.org/directory'
[Do 4. Aug 10:36:01 CEST 2022] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Do 4. Aug 10:36:01 CEST 2022] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
[Do 4. Aug 10:36:01 CEST 2022] _ACME_SERVER_PATH='directory'
[Do 4. Aug 10:36:01 CEST 2022] _stopRenewOnError
[Do 4. Aug 10:36:01 CEST 2022] _server
[Do 4. Aug 10:36:01 CEST 2022] _set_level='2'
[Do 4. Aug 10:36:01 CEST 2022] di='/root/.acme.sh/*.kandidaten-befragung.de/'
[Do 4. Aug 10:36:01 CEST 2022] d='*.kandidaten-befragung.de'
[Do 4. Aug 10:36:01 CEST 2022] _renewServer
[Do 4. Aug 10:36:01 CEST 2022] Using config home:/root/.acme.sh
[Do 4. Aug 10:36:01 CEST 2022] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Do 4. Aug 10:36:01 CEST 2022] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
[Do 4. Aug 10:36:01 CEST 2022] _ACME_SERVER_PATH='directory'
[Do 4. Aug 10:36:01 CEST 2022] DOMAIN_PATH='/root/.acme.sh/*.kandidaten-befragung.de'
[Do 4. Aug 10:36:01 CEST 2022] Renew: '*.kandidaten-befragung.de'
[Do 4. Aug 10:36:01 CEST 2022] Le_API='https://acme-v02.api.letsencrypt.org/directory'
[Do 4. Aug 10:36:01 CEST 2022] Renew to Le_API=https://acme-v02.api.letsencrypt.org/directory
[Do 4. Aug 10:36:01 CEST 2022] initpath again.
[Do 4. Aug 10:36:01 CEST 2022] Using config home:/root/.acme.sh
[Do 4. Aug 10:36:01 CEST 2022] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Do 4. Aug 10:36:01 CEST 2022] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
[Do 4. Aug 10:36:01 CEST 2022] _ACME_SERVER_PATH='directory'
[Do 4. Aug 10:36:01 CEST 2022] Skip, Next renewal time is: 2022-08-22T11:53:55Z
[Do 4. Aug 10:36:01 CEST 2022] Add '--force' to force to renew.
[Do 4. Aug 10:36:01 CEST 2022] Return code: 2
[Do 4. Aug 10:36:01 CEST 2022] Skipped *.kandidaten-befragung.de
[Do 4. Aug 10:36:01 CEST 2022] di='/root/.acme.sh/*.strausberg-design.de/'
[Do 4. Aug 10:36:01 CEST 2022] d='*.strausberg-design.de'
[Do 4. Aug 10:36:01 CEST 2022] _renewServer
[Do 4. Aug 10:36:01 CEST 2022] Using config home:/root/.acme.sh
[Do 4. Aug 10:36:01 CEST 2022] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Do 4. Aug 10:36:01 CEST 2022] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
[Do 4. Aug 10:36:01 CEST 2022] _ACME_SERVER_PATH='directory'
[Do 4. Aug 10:36:01 CEST 2022] DOMAIN_PATH='/root/.acme.sh/*.strausberg-design.de'
[Do 4. Aug 10:36:01 CEST 2022] Renew: '*.strausberg-design.de'
[Do 4. Aug 10:36:01 CEST 2022] Le_API='https://acme-v02.api.letsencrypt.org/directory'
[Do 4. Aug 10:36:01 CEST 2022] Renew to Le_API=https://acme-v02.api.letsencrypt.org/directory
[Do 4. Aug 10:36:01 CEST 2022] initpath again.
[Do 4. Aug 10:36:01 CEST 2022] Using config home:/root/.acme.sh
[Do 4. Aug 10:36:01 CEST 2022] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Do 4. Aug 10:36:01 CEST 2022] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
[Do 4. Aug 10:36:01 CEST 2022] _ACME_SERVER_PATH='directory'
[Do 4. Aug 10:36:01 CEST 2022] _main_domain='*.strausberg-design.de'
[Do 4. Aug 10:36:01 CEST 2022] _alt_domains='no'
[Do 4. Aug 10:36:01 CEST 2022] 'dns_doapi' does not contain 'dns'
[Do 4. Aug 10:36:01 CEST 2022] 'dns_doapi' does not contain 'dns'
[Do 4. Aug 10:36:01 CEST 2022] Le_NextRenewTime='1659391711'
[Do 4. Aug 10:36:01 CEST 2022] Using ACME_DIRECTORY: https://acme-v02.api.letsencrypt.org/directory
[Do 4. Aug 10:36:01 CEST 2022] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[Do 4. Aug 10:36:02 CEST 2022] GET
[Do 4. Aug 10:36:02 CEST 2022] url='https://acme-v02.api.letsencrypt.org/directory'
[Do 4. Aug 10:36:02 CEST 2022] timeout=
[Do 4. Aug 10:36:02 CEST 2022] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  --trace-ascii /tmp/tmp.M03tTRJbgY  -g '
[Do 4. Aug 10:36:02 CEST 2022] ret='0'
[Do 4. Aug 10:36:02 CEST 2022] response='{
  "ghQtRTfNn30": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}'
[Do 4. Aug 10:36:02 CEST 2022] ACME_KEY_CHANGE='https://acme-v02.api.letsencrypt.org/acme/key-change'
[Do 4. Aug 10:36:02 CEST 2022] ACME_NEW_AUTHZ
[Do 4. Aug 10:36:02 CEST 2022] ACME_NEW_ORDER='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Do 4. Aug 10:36:02 CEST 2022] ACME_NEW_ACCOUNT='https://acme-v02.api.letsencrypt.org/acme/new-acct'
[Do 4. Aug 10:36:02 CEST 2022] ACME_REVOKE_CERT='https://acme-v02.api.letsencrypt.org/acme/revoke-cert'
[Do 4. Aug 10:36:02 CEST 2022] ACME_AGREEMENT='https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf'
[Do 4. Aug 10:36:02 CEST 2022] ACME_NEW_NONCE='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Do 4. Aug 10:36:02 CEST 2022] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Do 4. Aug 10:36:02 CEST 2022] _on_before_issue
[Do 4. Aug 10:36:02 CEST 2022] _chk_main_domain='*.strausberg-design.de'
[Do 4. Aug 10:36:02 CEST 2022] _chk_alt_domains
[Do 4. Aug 10:36:02 CEST 2022] 'dns_doapi' does not contain 'no'
[Do 4. Aug 10:36:02 CEST 2022] Le_LocalAddress
[Do 4. Aug 10:36:02 CEST 2022] d='*.strausberg-design.de'
[Do 4. Aug 10:36:02 CEST 2022] Check for domain='*.strausberg-design.de'
[Do 4. Aug 10:36:02 CEST 2022] _currentRoot='dns_doapi'
[Do 4. Aug 10:36:02 CEST 2022] d
[Do 4. Aug 10:36:02 CEST 2022] 'dns_doapi' does not contain 'apache'
[Do 4. Aug 10:36:02 CEST 2022] _saved_account_key_hash='6qZ671aF6Vu3UipdB9MR84aCYRD3Gx6s1ScU2RoCOLQ='
[Do 4. Aug 10:36:02 CEST 2022] _saved_account_key_hash is not changed, skip register account.
[Do 4. Aug 10:36:02 CEST 2022] Read key length:2048
[Do 4. Aug 10:36:02 CEST 2022] _createcsr
[Do 4. Aug 10:36:02 CEST 2022] domain='*.strausberg-design.de'
[Do 4. Aug 10:36:02 CEST 2022] domainlist
[Do 4. Aug 10:36:02 CEST 2022] csrkey='/root/.acme.sh/*.strausberg-design.de/*.strausberg-design.de.key'
[Do 4. Aug 10:36:02 CEST 2022] csr='/root/.acme.sh/*.strausberg-design.de/*.strausberg-design.de.csr'
[Do 4. Aug 10:36:02 CEST 2022] csrconf='/root/.acme.sh/*.strausberg-design.de/*.strausberg-design.de.csr.conf'
[Do 4. Aug 10:36:02 CEST 2022] Single domain='*.strausberg-design.de'
[Do 4. Aug 10:36:02 CEST 2022] seg='--'
[Do 4. Aug 10:36:02 CEST 2022] _is_idn_d='*.strausberg-design.de'
[Do 4. Aug 10:36:02 CEST 2022] _idn_temp='srausbergdesignde'
[Do 4. Aug 10:36:02 CEST 2022] Please install idn to process IDN names.
[Do 4. Aug 10:36:02 CEST 2022] _is_idn_d='*.strausberg-design.de'
[Do 4. Aug 10:36:02 CEST 2022] _idn_temp='srausbergdesignde'
[Do 4. Aug 10:36:02 CEST 2022] Please install idn to process IDN names.
[Do 4. Aug 10:36:02 CEST 2022] _csr_cn
Error Loading request extension section v3_req
140433175794112:error:2206D06D:X509 V3 routines:X509V3_parse_list:invalid null value:../crypto/x509v3/v3_utl.c:379:
140433175794112:error:22097069:X509 V3 routines:do_ext_nconf:invalid extension string:../crypto/x509v3/v3_conf.c:93:name=subjectAltName,section=DNS:
140433175794112:error:22098080:X509 V3 routines:X509V3_EXT_nconf:error in extension:../crypto/x509v3/v3_conf.c:47:name=subjectAltName, value=DNS:
[Do 4. Aug 10:36:02 CEST 2022] Create CSR error.
[Do 4. Aug 10:36:02 CEST 2022] pid
[Do 4. Aug 10:36:02 CEST 2022] No need to restore nginx, skip.
[Do 4. Aug 10:36:02 CEST 2022] _clearupdns
[Do 4. Aug 10:36:02 CEST 2022] dns_entries
[Do 4. Aug 10:36:02 CEST 2022] skip dns.
[Do 4. Aug 10:36:02 CEST 2022] _on_issue_err
[Do 4. Aug 10:36:02 CEST 2022] Please add '--debug' or '--log' to check more details.
[Do 4. Aug 10:36:02 CEST 2022] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Do 4. Aug 10:36:02 CEST 2022] _chk_vlist
[Do 4. Aug 10:36:02 CEST 2022] 'dns_doapi' does not contain 'dns'
[Do 4. Aug 10:36:02 CEST 2022] socat doesn't exist.
[Do 4. Aug 10:36:02 CEST 2022] Diagnosis versions: 
openssl:openssl
OpenSSL 1.1.1  11 Sep 2018
apache:
apache doesn't exist.
nginx:
nginx version: nginx/1.14.0 (Ubuntu)
built with OpenSSL 1.1.1  11 Sep 2018
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fdebug-prefix-map=/build/nginx-KgqPmI/nginx-1.14.0=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fPIC' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --modules-path=/usr/lib/nginx/modules --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-debug --with-pcre-jit --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_v2_module --with-http_dav_module --with-http_slice_module --with-threads --with-http_addition_module --with-http_geoip_module=dynamic --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module=dynamic --with-http_sub_module --with-http_xslt_module=dynamic --with-stream=dynamic --with-stream_ssl_module --with-mail=dynamic --with-mail_ssl_module
socat:
[Do 4. Aug 10:36:02 CEST 2022] Return code: 1
[Do 4. Aug 10:36:02 CEST 2022] Error renew *.strausberg-design.de.
[Do 4. Aug 10:36:02 CEST 2022] _error_level='1'
[Do 4. Aug 10:36:02 CEST 2022] _set_level='2'
[Do 4. Aug 10:36:02 CEST 2022] Sending via: mail
[Do 4. Aug 10:36:02 CEST 2022] Found /root/.acme.sh/notify/mail.sh for mail
[Do 4. Aug 10:36:02 CEST 2022] _subject='Renew Error Skipped'
[Do 4. Aug 10:36:02 CEST 2022] _content='Error certs:
    *.strausberg-design.de

Skipped certs:
    *.kandidaten-befragung.de

'
[Do 4. Aug 10:36:02 CEST 2022] _statusCode='1'
[Do 4. Aug 10:36:03 CEST 2022] mail send success.
[Do 4. Aug 10:36:03 CEST 2022] mail Success
```

**Comment by hokascha** [comment]
Don't know if this is relevant to the issue, but notice the single "t" in the domain name that seems to be filtered along with special chars:
```
[Do 4. Aug 10:36:02 CEST 2022] _is_idn_d='*.strausberg-design.de'
[Do 4. Aug 10:36:02 CEST 2022] _idn_temp='srausbergdesignde'
```

**Comment by Neilpang** [comment]
what is your OS version.

We tested in openbsd 7.1 and 6.9.

https://github.com/acmesh-official/acmetest/actions/runs/2789817117

both passed.

**Comment by hokascha** [comment]
Ubuntu 18.04

**Comment by Neilpang** [comment]
@hokascha 

I tried the code in ubuntu 18.04:
```
 _is_idn_d='*.strausberg-design.de'

printf "%s" "$_is_idn_d" | tr -d [0-9] | tr -d [a-z] | tr -d [A-Z] | tr -d '*.,-_'

```

all the chars in the domain are trimed out.

please check it again.
if you still have problems, please create a new issue and provide log with `--debug 2`

thanks
