### ISSUE TITLE
Concatenate fullchain.cer file without empty lines - broken chain in haproxy

### ISSUE THREAD

**Issue by fliespl** [acmesh-official/acme.sh#4848]
Steps to reproduce
------------------
Generated fulchain file contains empty lines between certs. This causes haproxy to only load first certificate in chain.

**Comment by fliespl** [comment]
Confirming it's still an issue with newest version. Debug log makes no difference since issue is with outputted file.

**Comment by wlallemand** [comment]
looks like you are using https://github.com/acmesh-official/acme.sh/pull/4581, please report there. It was fixed in the PR.
The problem only exists with DEPLOY_HAPROXY_HOT_UPDATE=yes.

**Comment by machsix** [comment]
This issue still exists. Any update?

**Comment by wlallemand** [comment]
#4581 was merged, this issue can be closed.

**Comment by lildadou** [comment]
Still an issue, with and without `export DEPLOY_HAPROXY_HOT_UPDATE=yes`

**Comment by wlallemand** [comment]
@lildadou I don't understand how that could be possible, HAProxy does support empty lines in files, this could be an unrelated problem, could you provide the acme.sh debug log as well as your `haproxy -vv` ?

**Comment by lildadou** [comment]
@wlallemand as you requested:
```
acme@haproxy:~$ export
declare -x DEPLOY_HAPROXY_PEM_PATH="/etc/haproxy/certs"
declare -x DEPLOY_HAPROXY_STATS_SOCKET="/var/run/haproxy/admin.sock"
declare -x HOME="/var/lib/acme"
declare -x LANG="fr_FR.UTF-8"
declare -x LOGNAME="acme"
declare -x MAIL="/var/mail/acme"
declare -x OLDPWD="/root"
declare -x PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
declare -x PWD="/var/lib/acme"
declare -x SHELL="/bin/bash"
declare -x SHLVL="1"
declare -x SUDO_COMMAND="/bin/bash"
declare -x SUDO_GID="0"
declare -x SUDO_UID="0"
declare -x SUDO_USER="root"
declare -x TERM="linux"
declare -x USER="acme"

acme@haproxy:~$ haproxy -vv
HAProxy version 2.8.15-1~bpo12+1 2025/04/25 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2028.
Known bugs: http://www.haproxy.org/bugs/bugs-2.8.15.html
Running on: Linux 6.8.12-10-pve #1 SMP PREEMPT_DYNAMIC PMX 6.8.12-10 (2025-04-18T07:39Z) x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = x86_64-linux-gnu-gcc
  CFLAGS  = -O2 -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_SYSTEMD=1 USE_OT=1 USE_QUIC=1 USE_PROMEX=1 USE_PCRE2=1 USE_PCRE2_JIT=1 USE_QUIC_OPENSSL_COMPAT=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_WOLFSSL +OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION +QUIC +QUIC_OPENSSL_COMPAT +RT +SHM_OPEN +SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=2).
Built with OpenSSL version : OpenSSL 3.0.15 3 Sep 2024
Running on OpenSSL version : OpenSSL 3.0.15 3 Sep 2024
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
OpenSSL providers loaded : default
Built with Lua version : Lua 5.3.6
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with OpenTracing support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.42 2022-12-11
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 12.2.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
       quic : mode=HTTP  side=FE     mux=QUIC  flags=HTX|NO_UPG|FRAMED
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
        [BWLIM] bwlim-in
        [BWLIM] bwlim-out
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [  OT] opentracing
        [SPOE] spoe
        [TRACE] trace

acme@haproxy:~$ acme.sh -v
https://github.com/acmesh-official/acme.sh
v3.0.6

acme@haproxy:~$ acme.sh --debug 2 --deploy --domain my.domain --deploy-hook haproxy
[lun. 28 avril 2025 15:03:07 CEST] _is_idn_d='my.domain'
[lun. 28 avril 2025 15:03:07 CEST] _idn_temp
[lun. 28 avril 2025 15:03:07 CEST] Lets find script dir.
[lun. 28 avril 2025 15:03:07 CEST] _SCRIPT_='/usr/local/bin/acme.sh'
[lun. 28 avril 2025 15:03:07 CEST] _script='/opt/acme/sh/acme.sh'
[lun. 28 avril 2025 15:03:07 CEST] _script_home='/opt/acme/sh'
[lun. 28 avril 2025 15:03:07 CEST] Using default home:/var/lib/acme/.acme.sh
[lun. 28 avril 2025 15:03:07 CEST] Using config home:/var/lib/acme/.acme.sh
[lun. 28 avril 2025 15:03:07 CEST] LE_WORKING_DIR='/var/lib/acme/.acme.sh'
https://github.com/acmesh-official/acme.sh
v3.0.6
[lun. 28 avril 2025 15:03:07 CEST] Running cmd: deploy
[lun. 28 avril 2025 15:03:07 CEST] Using config home:/var/lib/acme/.acme.sh
[lun. 28 avril 2025 15:03:07 CEST] default_acme_server
[lun. 28 avril 2025 15:03:07 CEST] ACME_DIRECTORY='https://acme.zerossl.com/v2/DV90'
[lun. 28 avril 2025 15:03:07 CEST] _ACME_SERVER_HOST='acme.zerossl.com'
[lun. 28 avril 2025 15:03:07 CEST] _ACME_SERVER_PATH='v2/DV90'
[lun. 28 avril 2025 15:03:07 CEST] The domain 'my.domain' seems to have a ECC cert already, lets use ecc cert.
[lun. 28 avril 2025 15:03:07 CEST] DOMAIN_PATH='/var/lib/acme/.acme.sh/certs/my.domain_ecc'
[lun. 28 avril 2025 15:03:07 CEST] DOMAIN_CONF='/var/lib/acme/.acme.sh/certs/my.domain_ecc/my.domain.conf'
[lun. 28 avril 2025 15:03:07 CEST] _deployApi='/opt/acme/sh/deploy/haproxy.sh'
[lun. 28 avril 2025 15:03:07 CEST] _cdomain='my.domain'
[lun. 28 avril 2025 15:03:07 CEST] _ckey='/var/lib/acme/.acme.sh/certs/my.domain_ecc/my.domain.key'
[lun. 28 avril 2025 15:03:07 CEST] _ccert='/var/lib/acme/.acme.sh/certs/my.domain_ecc/my.domain.cer'
[lun. 28 avril 2025 15:03:07 CEST] _cca='/var/lib/acme/.acme.sh/certs/my.domain_ecc/ca.cer'
[lun. 28 avril 2025 15:03:07 CEST] _cfullchain='/var/lib/acme/.acme.sh/certs/my.domain_ecc/fullchain.cer'
[lun. 28 avril 2025 15:03:07 CEST] DEPLOY_HAPROXY_PEM_PATH='/etc/haproxy/certs'
[lun. 28 avril 2025 15:03:07 CEST] PEM_PATH /etc/haproxy/certs exists
[lun. 28 avril 2025 15:03:07 CEST] DEPLOY_HAPROXY_PEM_NAME
[lun. 28 avril 2025 15:03:07 CEST] DEPLOY_HAPROXY_BUNDLE
[lun. 28 avril 2025 15:03:07 CEST] DEPLOY_HAPROXY_ISSUER
[lun. 28 avril 2025 15:03:07 CEST] DEPLOY_HAPROXY_RELOAD
[lun. 28 avril 2025 15:03:07 CEST] DEPLOY_HAPROXY_HOT_UPDATE
[lun. 28 avril 2025 15:03:07 CEST] DEPLOY_HAPROXY_STATS_SOCKET='/var/run/haproxy/admin.sock'
[lun. 28 avril 2025 15:03:07 CEST] _suffix
[lun. 28 avril 2025 15:03:07 CEST] Deploying PEM file
[lun. 28 avril 2025 15:03:07 CEST] _temppem='/tmp/tmp.pmjKNbOHqe'
[lun. 28 avril 2025 15:03:07 CEST] Moving new certificate into place
[lun. 28 avril 2025 15:03:07 CEST] _pem='/etc/haproxy/certs/my.domain.pem'
[lun. 28 avril 2025 15:03:07 CEST] _socat_cert_cmd='echo 'show ssl cert' | socat /var/run/haproxy/admin.sock - | grep -q '^/etc/haproxy/certs/my.domain.pem$''
[lun. 28 avril 2025 15:03:07 CEST] Update existing certificate '/etc/haproxy/certs/my.domain.pem' over HAProxy stats socket.
[lun. 28 avril 2025 15:03:07 CEST] _socat_cert_set_cmd='echo -e 'set ssl cert /etc/haproxy/certs/my.domain.pem <<\n-----BEGIN EC PRIVATE KEY-----
MH...==
-----END EC PRIVATE KEY-----
-----BEGIN CERTIFICATE-----
MII...6ZQ==
-----END CERTIFICATE-----

-----BEGIN CERTIFICATE-----
MIIEV...H04=
-----END CERTIFICATE-----\n' | socat 'UNIX:/var/run/haproxy/admin.sock' - | grep -q 'Transaction created''
2025/04/28 15:03:07 socat[26269] E write(1, 0x599943055000, 793): Broken pipe
[lun. 28 avril 2025 15:03:07 CEST] _socat_cert_commit_cmd='echo 'commit ssl cert /etc/haproxy/certs/my.domain.pem' | socat 'UNIX:/var/run/haproxy/admin.sock' - | grep -q '^Success!$''
[lun. 28 avril 2025 15:03:07 CEST] Success
```

**Comment by wlallemand** [comment]
I'm confused, you are using acme.sh 3.0.6 but this feature was merged in 3.0.8, did you copy an older version of the deploy script from somewhere else? There is a sanitizer in the current deploy script, you shouldn't have this problem.

**Comment by lildadou** [comment]
> I'm confused, you are using acme.sh 3.0.6 but this feature was merged in 3.0.8, did you copy an older version of the deploy script from somewhere else? There is a sanitizer in the current deploy script, you shouldn't have this problem.

I followed these instructions (2023-07-13 acme.sh was at v3.0.6): https://www.haproxy.com/blog/haproxy-and-let-s-encrypt

**Comment by wlallemand** [comment]
You probably installed this when the haproxy.sh deploy script was not merged in acme.sh yet, there were fixes since then. I'm not sure what's going on with your install, but this was fixed before merging, the article was also modified to stop downloading the deploy script fork so you shouldn't have problem anymore if you follow the same procedure.

**Comment by lildadou** [comment]
Ok, i had some troubles against `$PATH`
I cannot reproduce the bug anymore with acme.sh v3.1.1

**Comment by wlallemand** [comment]
Okay, thanks, Issue can be closed.

**Comment by neilpang** [comment]
Closing per the thread: the empty-line sanitizer shipped with the merged haproxy deploy hook (3.0.8+), the remaining report turned out to be a stale pre-merge copy of the script, and it's not reproducible on current releases.
