### ISSUE TITLE
Enable log by default in docker image

### ISSUE THREAD

**Issue by hlavki** [acmesh-official/acme.sh#992]
There is no log in docker image. It should be fine to enable log by default and send it to STDOUT.

**Comment by Neilpang** [comment]
good idea.

**Comment by JohnGalt1717** [comment]
Any word on this or way to enable this via configuration?

**Comment by Neilpang** [comment]
There is already simple output message to the STDOUT,   is that enough?

If you need more detail log, you can enable log manully.

**Comment by JohnGalt1717** [comment]
It isn’t dumping anything with docker logs.  I would expect to see everything that goes to the log file also spit out to docker logs.

**Comment by sjtuross** [comment]
@Neilpang Sorry to tag you. Any chance to merge this PR #2609?

**Comment by Neilpang** [comment]
@sjtuross  I just fixed the image.  The `crond` is the `1`st pid in the container now.   acme.sh will ouput the logs to the `crond` process.  so you can use `docker logs` to see the logs.

**Comment by sjtuross** [comment]
@Neilpang Thank you. I tried the latest docker image neilpang/acme.sh:dev. The weird issue is that when cron job runs, I only see the below error log, but I don't have any email notification set up. If I manually run the same command from cron job in the container console, it runs properly. Any idea? I feel the upgrade to alpine:3.17 is suspicious.

```
/usr/sbin/sendmail: unrecognized option: F
BusyBox v1.35.0 (2022-11-19 10:13:10 UTC) multi-call binary.
Usage: sendmail [-tv] [-f SENDER] [-amLOGIN 4<user_pass.txt | -auUSER -apPASS]
		[-w SECS] [-H 'PROG ARGS' | -S HOST] [RECIPIENT_EMAIL]...
Read email from stdin and send it
Standard options:
	-t		Read additional recipients from message body
	-f SENDER	For use in MAIL FROM:<sender>. Can be empty string
			Default: -auUSER, or username of current UID
	-o OPTIONS	Various options. -oi implied, others are ignored
	-i		-oi synonym, implied and ignored
Busybox specific options:

	-v		Verbose
	-w SECS		Network timeout
	-H 'PROG ARGS'	Run connection helper. Examples:
		openssl s_client -quiet -tls1 -starttls smtp -connect smtp.gmail.com:25
		openssl s_client -quiet -tls1 -connect smtp.gmail.com:465
			$SMTP_ANTISPAM_DELAY: seconds to wait after helper connect
	-S HOST[:PORT]	Server (default $SMTPHOST or 127.0.0.1)
	-amLOGIN	Log in using AUTH LOGIN
	-amPLAIN	or AUTH PLAIN
			(-amCRAM-MD5 not supported)
	-auUSER		Username for AUTH
	-apPASS 	Password for AUTH
If no -a options are given, authentication is not done.
If -amLOGIN is given but no -au/-ap, user/password is read from fd #4.
Other options are silently ignored; -oi is implied.
Use makemime to create emails with attachments.
```

**Comment by Neilpang** [comment]
@sjtuross  fixed.  please try again.

**Comment by sjtuross** [comment]
@Neilpang the sendmail issue is gone, but it seems the cron job execution log is still missing from `docker logs` unless I apply the change from this PR #2609.

**Comment by Neilpang** [comment]
applied,  please try again.

**Comment by sjtuross** [comment]
It works now! Thanks again!

**Comment by Neilpang** [comment]
I will merge it to master soon.
